apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
        - name: counter-backend
          image: ghcr.io/isaaclins/counter-backend:v1
          imagePullPolicy: Always
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db-host
                name: counter-backend-config
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: counter-database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: counter-database
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: counter-database
