apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend-deployment
  labels:
    app: counter-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-frontend
          image: ghcr.io/isaaclins/counter-frontend:v1
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: https://counter-backend-route-233756-ilins1.apps.exoscale-ch-gva-2-0.appuio.cloud/
            - name: npm_config_cache
              value: ./.npm-cache
