apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend-deployment
  labels:
    app: counter-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
        - name: counter-backend
          image: ghcr.io/modul-i-ch-109/kube_solution/counter_backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: counter-database
            - name: npm_config_cache
              value: ./.npm-cache
